# Generated by Django 4.2.29 on 2026-04-25 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_systemlog_user_alter_systemlog_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='latest_disk_free',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='latest_disk_total',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
