# Generated by Django 4.2.29 on 2026-04-27 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_userprofile_latest_disk_free_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='cores',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='os_sys',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='processor',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='ram_total',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='uptime_hours',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
